before:
  hooks:
    - go mod tidy
builds:
  - id: server
    main: ./main.go
    binary: tsddcli
    ldflags:
      - -w -s
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.CommitDate={{.Timestamp}}
    tags:
      - release
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    # We currently cannot run mysqlbinlog on arm64.
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc    
archives:
  - name_template: "tsddcli-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "tsddcli-linux-checksums.txt"  