before:
  hooks:
    - go mod tidy
builds:
  - id: server
    main: ./main.go
    binary: tsddcli
    ldflags:
      - -w -s
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.CommitDate={{.Timestamp}}
    tags:
      - release
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "tsddcli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "tsddcli_darwin_{{ .Version }}_checksums.txt"   